### PR TITLE
[FIX] Last day separator sometimes not showing

### LINKED ISSUE #957: [BUG] Date mark in chat from last day is not visible
- Your Rocket.Chat app version: 1.7.2(115)
- Your Rocket.Chat server version: 0.59.3
- Device (or Simulator) you're running with: iPhone 6 Plus

The date mark is reproducible not correctly displayed if I connect the first time this day to the channel:

image1

If I just sent the app to the background and start it again  (reconnection occurs) the date mark is correctly displayed:

image2

### PR DESCRIPTION
**Pull request by cardoso**
@RocketChat/ios

Closes #957

### CODE REVIEW

File: Rocket.ChatTests/Extensions/DateExtensionsSpec.swift [hunk 1]
```diff
@@ -43,4 +43,14 @@ class DateExtension: XCTestCase {
...
 
+    func testSameDayAs() {
+        let date = Date()
+        XCTAssertTrue(date.sameDayAs(date))
+
+        let oneDay = 86400.0
+        let date2 = date.addingTimeInterval(oneDay)
+
+        XCTAssertFalse(date.sameDayAs(date2))
+    }
```
Comment (rafaelks) [inline Rocket.ChatTests/Extensions/DateExtensionsSpec.swift]: ✅

**Comment by rafaelks** [comment]
@cardoso I think this PR introduced this bug:

simulator screen shot - iphone se - 2017-11-25 at 07 42 53
